build:
  maxIssues: 0  # 이슈 1개라도 있으면 실패

# 코드 복잡도 설정
complexity:
  LongMethod:
    active: true
    threshold: 60  # 함수의 길이가 60을 넘으면 경고

  LongParameterList:
    active: true
    functionThreshold: 6  # 일반 함수는 최대 6개 파라미터
    constructorThreshold: 8  # 생성자는 최대 8개 파라미터

  TooManyFunctions:
    active: true
    thresholdInClasses: 15  # 클래스에 최대 15개 함수

  CyclomaticComplexMethod:
    active: true
    threshold: 15  # if / when / for 등 최대 15

# 가독성과 일관성 유지
style:
  MagicNumber:
    active: true
    # Detekt 버그로 인해 MagicNumber 문자열로 변경
    ignoreNumbers: ["-1", "0", "1", "8", "16", "24", "32"]  # -1 / 0 / 1 / UI에서 자주 사용하는 숫자 제외 의미없는 숫자 사용 금지
    ignorePropertyDeclaration: true

  ReturnCount:
    active: true
    max: 3  # 한 함수 내 return 문 최대 3개

  UnusedPrivateMember:
    active: true  # 사용하지 않는 private 변수나 함수 금지

  ExpressionBodySyntax:
    active: true # 한 줄짜리 함수는 단일 표현식 사용

  MaxLineLength:
    active: true
    maxLineLength: 120  # 한 줄 최대 길이 120자

# 명명 규칙
naming:
  FunctionNaming:
    active: true
    functionPattern: '[a-z][A-Za-z0-9]*'  # 함수 이름은 소문자로 시작하는 카멜 케이스
    ignoreAnnotated:
      - Composable

  VariableNaming:
    active: true  # 변수 이름 표준 규칙 강제

# 성능
performance:
  SpreadOperator:
    active: true  # 가변 인자 * 사용 제한
